# Generated by Django 5.2.11 on 2026-02-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('london_housing', '0002_housing_for_rent_housing_for_sale_porfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
