# Generated by Django 5.2.11 on 2026-03-02 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('london_housing', '0003_housing_average_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porfolio',
            new_name='Portfolio',
        ),
    ]
