# Generated by Django 5.2.11 on 2026-03-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('london_housing', '0004_rename_porfolio_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='receptions',
        ),
    ]
