# Generated by Django 5.2.11 on 2026-03-07 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('london_housing', '0005_remove_housing_receptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('LIVING', 'Living at this address'), ('SELLING', 'Trying to sell'), ('RENTING', 'Trying to rent out'), ('ACIVE_TENANT', 'Currently renting out')], default='LIVING', max_length=20),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_rent_pcm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy', to='london_housing.portfolio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'housing')},
            },
        ),
    ]
